version: "3.9"

services:
    database:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379

    # app:
    #     build: .
    #     container_name: rentx
    #     restart: always
    #     ports:
    #         - 7000:7000
    #         - 9000:9000
    #     volumes:
    #         - .:/usr/app
    #     links:
    #         - database
    #     depends_on:
    #         - database

volumes:
    pgdata:
        driver: local
